/* Remember enable DBMS_OUTPUT in Oracle SQL Developer */

/* PKG_PRODUCT.TOTALCOUNT */
DECLARE
    RETURN INT;
BEGIN
    SELECT PKG_PRODUCT.TOTALCOUNT INTO RETURN FROM DUAL;
    DBMS_OUTPUT.PUT_LINE('total records '||RETURN);
END;

/* PKG_PRODUCT.QUERY_PRODUCT */
DECLARE
	P_CODE		VARCHAR2(20);
	P_NAME		NVARCHAR2(50);
	
    ID			INT;
    CODE		VARCHAR2(20);
    NAME		NVARCHAR2(50);
    RECORD      INT;
	O_COUNT		SYS_REFCURSOR;
    O_RETURN	SYS_REFCURSOR;
BEGIN
	P_CODE := '001';
	P_NAME := NULL;
	
    PKG_PRODUCT.QUERY_PRODUCT(P_CODE,P_NAME,O_COUNT,O_RETURN);
    
    LOOP
        FETCH O_COUNT
            INTO RECORD;
            EXIT WHEN O_COUNT%NOTFOUND;
            
            DBMS_OUTPUT.PUT_LINE('Total records: '||RECORD);
    END LOOP;
    CLOSE O_COUNT;
    
    DBMS_OUTPUT.PUT_LINE('Data:');
    LOOP 
        FETCH O_RETURN
            INTO ID,CODE,NAME;
            EXIT WHEN O_RETURN%NOTFOUND;
            
            DBMS_OUTPUT.PUT_LINE(ID||','||CODE||','||NAME);
    END LOOP;
    CLOSE O_RETURN;
    
END;

/* PKG_PRODUCT.GET_PRODUCT */
DECLARE
    ID INT;
    CODE VARCHAR2(20);
    NAME NVARCHAR2(50);    
    RETURN SYS_REFCURSOR;
BEGIN
    ID := 1;
    
    PKG_PRODUCT.GET_PRODUCT(ID,RETURN);
    
    DBMS_OUTPUT.PUT_LINE('Get Product by Id = '||ID);
    DBMS_OUTPUT.PUT_LINE('Data:');
    LOOP 
        FETCH RETURN
            INTO ID,CODE,NAME;
            EXIT WHEN RETURN%NOTFOUND;
            
            DBMS_OUTPUT.PUT_LINE(ID||','||CODE||','||NAME);
    END LOOP;
    CLOSE RETURN;
END;

/* PKG_PRODUCT.CREATE_PRODUCT */
DECLARE
    ID INT;
    CODE VARCHAR2(20);
    NAME NVARCHAR2(50);
BEGIN
    CODE := 'TEST-CODE';
    NAME := 'TEST-NAME';
    
    PKG_PRODUCT.CREATE_PRODUCT(CODE,NAME,ID);
    
    DBMS_OUTPUT.PUT_LINE('New Product Id is '||ID);
END;

/* PKG_PRODUCT.UPDATE_PRODUCT */
DECLARE
    ID INT;
    CODE VARCHAR2(20);
    NAME NVARCHAR2(50);
    RESULT CHAR(1);
BEGIN
    ID := 5;
    CODE := 'AODE00';
    NAME := 'AAME00';
    
    PKG_PRODUCT.UPDATE_PRODUCT(CODE,NAME,ID,RESULT);
    
    DBMS_OUTPUT.PUT_LINE('Product update result is '||RESULT);
END;

/* PKG_PRODUCT.DELETE_PRODUCT */
DECLARE
	ID INT;
	RESULT CHAR(1);
BEGIN
	ID := 5;
	
	PKG_PRODUCT.DELETE_PRODUCT(ID,RESULT);
	
    DBMS_OUTPUT.PUT_LINE('Delete product Id='||ID||', result '||RESULT);
END;